(ns kami.app-nle.ui
  (:require [reagent.core :as r] [reagent.dom.client :as rdom] [kami.app-nle.core :as nle]))

(def sample (nle/project {:project/id "demo-cut" :project/name "海辺の予告編" :project/fps 30
 :project/tracks [{:track/id "v2" :track/name "V2 • Titles" :track/type :video :track/clips [{:clip/id "title" :clip/name "OPENING" :clip/start-frame 45 :clip/in-frame 0 :clip/out-frame 75 :clip/color "#fbbf24"}]}
 {:track/id "v1" :track/name "V1 • Picture" :track/type :video :track/clips [{:clip/id "wide" :clip/name "Wide shot" :clip/source-id "asset:0" :clip/start-frame 0 :clip/in-frame 20 :clip/out-frame 170 :clip/color "#38bdf8"} {:clip/id "close" :clip/name "Close up" :clip/source-id "asset:1" :clip/start-frame 150 :clip/in-frame 10 :clip/out-frame 130 :clip/color "#a78bfa"}]}
 {:track/id "a1" :track/name "A1 • Dialogue" :track/type :audio :track/clips [{:clip/id "dialogue" :clip/name "Dialogue.wav" :clip/start-frame 30 :clip/in-frame 0 :clip/out-frame 240 :clip/color "#34d399"}]}]}))
(defonce state (r/atom {:project sample :frame 105 :playing? false :selected "wide" :assets {} :active-source nil :pending-source-frame 0 :decoded? false :effect :none :exporting? false}))
(defonce video-node (atom nil)) (defonce canvas-node (atom nil)) (defonce media-url (atom nil))
(def filters {:none "none" :cinema "contrast(1.18) saturate(1.22)" :mono "grayscale(1) contrast(1.12)" :dream "saturate(1.35) brightness(1.08) blur(1px)"})
(defn draw-frame! [] (when (and @video-node @canvas-node) (let [v @video-node c @canvas-node ctx (.getContext c "2d")] (when (>= (.-readyState v) 2) (set! (.-filter ctx) (get filters (:effect @state) "none")) (.drawImage ctx v 0 0 (.-width c) (.-height c)) (swap! state assoc :frame (js/Math.floor (* (.-currentTime v) (get-in @state [:project :project/fps]))))) (js/requestAnimationFrame draw-frame!))))
(defn activate-source! [source-id source-frame] (when-let [{:keys [url]} (get-in @state [:assets source-id])] (swap! state assoc :pending-source-frame source-frame :active-source source-id) (if (not= url (.-src @video-node)) (do (set! (.-src @video-node) url) (.load @video-node)) (set! (.-currentTime @video-node) (/ source-frame (get-in @state [:project :project/fps]))))))
(defn seek-frame! [frame] (when-let [clip (nle/clip-at-frame (:project @state) frame)] (activate-source! (:clip/source-id clip) (+ (:clip/in-frame clip) (- frame (:clip/start-frame clip))))))
(defn load-media! [e] (let [files (array-seq (.. e -target -files))] (doseq [[index file] (map-indexed vector files)] (let [source-id (str "asset:" index) url (js/URL.createObjectURL file)] (swap! state assoc-in [:assets source-id] {:name (.-name file) :url url}))) (when (seq files) (seek-frame! (:frame @state)))))
(defn media-ready! [] (let [v @video-node c @canvas-node] (set! (.-width c) (or (.-videoWidth v) 1280)) (set! (.-height c) (or (.-videoHeight v) 720)) (set! (.-currentTime v) (/ (:pending-source-frame @state) (get-in @state [:project :project/fps]))) (swap! state assoc :decoded? true) (draw-frame!)))
(defn toggle-play! [] (when (:decoded? @state) (if (:playing? @state) (.pause @video-node) (.play @video-node)) (swap! state update :playing? not)))
(defn download-blob! [blob] (let [url (js/URL.createObjectURL blob) a (.createElement js/document "a")] (set! (.-href a) url) (set! (.-download a) "kami-nle-master.webm") (.click a) (js/setTimeout #(js/URL.revokeObjectURL url) 1000)))
(defn export-webm! [] (when (:decoded? @state) (let [stream (.captureStream @canvas-node (get-in @state [:project :project/fps])) source (when (.-captureStream @video-node) (.captureStream @video-node)) audio (when source (first (array-seq (.getAudioTracks source)))) _ (when audio (.addTrack stream audio)) recorder (js/MediaRecorder. stream #js {:mimeType "video/webm;codecs=vp8,opus"}) chunks (array)] (swap! state assoc :exporting? true) (set! (.-ondataavailable recorder) #(when (pos? (.. % -data -size)) (.push chunks (.-data %)))) (set! (.-onstop recorder) #(do (download-blob! (js/Blob. chunks #js {:type "video/webm"})) (swap! state assoc :exporting? false :playing? false))) (set! (.-onended @video-node) #(.stop recorder)) (set! (.-currentTime @video-node) 0) (.start recorder 250) (.play @video-node) (swap! state assoc :playing? true))))
(defn clip-view [c total] [:button.clip {:class (when (= (:selected @state) (:clip/id c)) "selected") :style {:left (str (* 100 (/ (:clip/start-frame c) total)) "%") :width (str (* 100 (/ (- (:clip/out-frame c) (:clip/in-frame c)) total)) "%") :background (:clip/color c)} :on-click #(swap! state assoc :selected (:clip/id c) :frame (:clip/start-frame c))} (:clip/name c)])
(defn app [] (let [{:keys [project frame playing? selected decoded? assets effect exporting?]} @state total (max 300 (nle/duration-frames project)) fps (:project/fps project)]
 [:main [:header [:div [:small "KOTOBA-LANG / VIDEO"] [:h1 "KAMI NLE"]] [:div.transport [:button.primary {:on-click toggle-play! :disabled (not decoded?)} (if playing? "❚❚ Pause" "▶ Play decoded media")] [:output (nle/timecode frame fps)]]]
  [:section.workspace [:aside [:h2 "Project bin"] [:label.import "Import V1 videos" [:input {:type "file" :accept "video/*" :multiple true :on-change load-media!}]] (if (seq assets) (for [[id asset] assets] ^{:key id} [:div.asset (str "🎞 " id " • " (:name asset))]) [:div.asset "No media loaded"]) [:label "Effect" [:select {:value (name effect) :on-change #(swap! state assoc :effect (keyword (.. % -target -value)))} [:option {:value "none"} "None"] [:option {:value "cinema"} "Cinema"] [:option {:value "mono"} "Monochrome"] [:option {:value "dream"} "Dream"]]] [:button {:on-click export-webm! :disabled (or (not decoded?) exporting?)} (if exporting? "Encoding WebM…" "Export WebM")] [:button {:on-click #(js/navigator.clipboard.writeText (pr-str project))} "Copy project EDN"]]
   [:div.monitor [:video {:ref #(reset! video-node %) :style {:display "none"} :plays-inline true :on-loaded-metadata media-ready! :on-pause #(swap! state assoc :playing? false)}] [:div.frame [:span "PROGRAM"] [:strong (nle/timecode frame fps)] [:canvas {:ref #(reset! canvas-node %) :aria-label "Decoded video preview"}] (when-not decoded? [:div.scene "IMPORT VIDEO"])] [:div.tools [:button {:disabled (nil? selected) :on-click #(swap! state update :project nle/split-clip selected frame (str selected "-b"))} "Split at playhead"] [:span (str fps " fps • " total " frames • " (name effect))]]]]
  [:section.timeline [:input.scrub {:type "range" :min 0 :max total :value frame :aria-label "Playhead" :on-change #(let [f (js/parseInt (.. % -target -value))] (swap! state assoc :frame f) (seek-frame! f))}] (for [track (:project/tracks project)] ^{:key (:track/id track)} [:div.track [:div.track-name (:track/name track)] [:div.lane (for [c (:track/clips track)] ^{:key (:clip/id c)} [clip-view c total])]])]
  [:footer (if-let [e (seq (nle/validate-project project))] (str "Errors: " e) "HTMLVideo decode • canvas effects • MediaRecorder WebM export")]]))
(defonce root-node (atom nil))
(defn init! [] (when-not @root-node (reset! root-node (rdom/create-root (.getElementById js/document "app")))) (rdom/render @root-node [app]))
